# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1eae76345f47cc88abd56ecbac6583bcdcd22c805735f0bd12c8c084f703556e4345f4754d4dbbab8c945a4b07bbbd2d1ab85476ec2c2ac19133fc448eb75c2

test:
  secret_key_base: 7337bb1e5359197662a5f61a54d59de656fa785b1f3fa5f865c61b1d971a9b5a02214ace913bd518a4d22ab679d187e8a8dd9c5ae2f8d1929f0331e6942eaa82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
